### ISSUE TITLE
Error in curl_fetch_memory(smtp_server, handle = h) : Login denied

### ISSUE THREAD

**Issue by sanjmeh** [rstudio/blastula#222]
Following line gives the above error:
`smtp_send(g1, to = "abc@gmail.com",subject = "renewed testing",credentials = creds_key("gmail"),from="EH")`

where `abc` to be replaced by an email.
where g1 is an email object created through `compose_email`

`g1 <- compose_email(body = "This is a test message, at 23 hours")`

I have regenerated the credentials by 

```
create_smtp_creds_key(
    id = "gmail",
    user = "xyz@gmail.com",
    host = "smtp.gmail.com",
    port = 465,
    use_ssl = TRUE
)
```

What could be going wrong when the same code used to work in May. Something happened in last few months that now the same code fails with the error.

**Comment by brian-law-rstudio** [comment]
I am experiencing a similar error. Thanks for posting sanjmeh

**Comment by rich-iannone** [comment]
When creating the credentials could you try using `provider = gmail`? I believe the `use_ssl` setting is wrong but the provider setting should give you the right SMTP configuration settings.

**Comment by brian-law-rstudio** [comment]
Culprit found! Gmail will automatically turn off the "less secure apps" setting without asking you, after some period of non-use. If you go here (https://myaccount.google.com/lesssecureapps) you can turn it back on. Hope that fixes it for you too sanjmeh!

-Brian

**Comment by sanjmeh** [comment]
Thanks @brian-law-rstudio 👍🏼  
Although I could not find the exact place in google console where I can turn it back on but will look into it once again. It will be nice if you could post the exact steps inside google console. The google console indeed has a full maze of options.

**Comment by brian-law-rstudio** [comment]
It is indeed a maze of options. I found that when I am logged into gmail, then if I click the link above it automatically took me to the right place.
