### ISSUE TITLE
Error in curl_fetch_memory(smtp_server, handle = h) : Login denied

### ISSUE THREAD

**Issue by latlio** [rstudio/blastula#228]
I've tried the following things already:

- specifying `smtp_send(..., credentials = blastula::creds(
          user = "myemail@gmail.com",
          provider = "gmail")
        )`
- `blastula::create_smtp_creds_key(
  id = "gmail",
  user = "myemail@gmail.com",
  provider = "gmail",
  use_ssl = TRUE
)`
- allowing access within my gmail account for SMTP/3rd party access
- re-installing the most recent versions of curl and blastula

I'm not sure what else to try, and I don't understand fundamentally why I'm getting this error message.

**Comment by cody-dubya** [comment]
@latlio If you are using 2-Step Verification when logging into Google, you'll need to create an App Password. Then you can use that newly created App Password when running `create_smtp_creds_key`

You can learn more about it [here](https://support.google.com/accounts/answer/185833)

One thing to highlight in the documentation:

> To help protect your account, we revoke your App Passwords when you change your Google Account password.

**Comment by PsychlytxTD** [comment]
I think the authors of this package need to offer more guidance in the documentation around credentials-related issues — getting this right isn't always straight forward. I was only able to send Blastula emails through SMTP with Gsuite after enabling 'less secure apps' within my Gsuite console. I can't see this mentioned anywhere in the documentation.

**Comment by JohnCoene** [comment]
I believe this is gmail blocking the sign in, the way this can be bypassed is by enabling "less secure apps" in [Google's global security settings](https://myaccount.google.com/security)

![image](https://user-images.githubusercontent.com/7833796/94784471-7ff76c80-03ce-11eb-86fd-369191f0ff07.png)

However, this understandably is not recommended: I'm not sure authors of the package should truly "encourage" this.

**Comment by pschloss** [comment]
I'm not using 2FA and I have less secure app access set to on as @JohnCoene indicated above and am still running into this problem...

```
create_smtp_creds_key(
  id = "gmail",
  user = "address1@gmail.com",
  provider = "gmail", overwrite=TRUE
)

test_message <- prepare_test_message()

test_message %>%
  smtp_send(
    from = "address1@gmail.com",
    to = "address2@gmail.com",
    subject = "Testing the `smtp_send()` function",
    credentials = creds_key("gmail")
 #   credentials = blastula::creds(user = "address1@gmail.com", provider="gmail")
  )
```

Neither approach to setting the credentials in `smtp_send` is working. My error message is the same as the title of this thread...

```
Error in curl_fetch_memory(smtp_server, handle = h) : Login denied
```


Here are my details:

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] blastula_0.3.2

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    getPass_0.2-2     uuid_0.1-4        tidyselect_1.1.0 
 [6] R6_2.5.0          rlang_0.4.10      fansi_0.4.2       blob_1.2.1        dplyr_1.0.5      
[11] tools_4.0.3       utf8_1.2.1        cli_2.5.0         DBI_1.1.0         commonmark_1.7   
[16] htmltools_0.5.1.1 ellipsis_0.3.1    assertthat_0.2.1  digest_0.6.27     tibble_3.1.1     
[21] lifecycle_1.0.0   crayon_1.4.1      keyring_1.1.0     purrr_0.3.4       vctrs_0.3.7      
[26] curl_4.3          glue_1.4.2        compiler_4.0.3    pillar_1.6.0      generics_0.1.0   
[31] jsonlite_1.7.2    pkgconfig_2.0.3  
```

**Comment by iNANOV** [comment]
Hello,

please Login into 

https://accounts.google.com/DisplayUnlockCaptcha

and try directly after to send email via your script.

**Comment by mxblsdl** [comment]
Just a note that @cody-dubya solution of creating an app password worked for me. I think the 'allow less secure apps' security option for google will also work, but the app password seems like a more secure choice.

I agree that there could be better documentation around this issue since programmatic access to a personal email is a very sensitive issue.

**Comment by latlio** [comment]
Closing this issue with official documentation from the maintainers of blastula: https://rstudio.github.io/blastula/articles/sending_using_smtp.html

Thanks everyone for your comments, and hope future readers who stumble across this thread resolve their issue!

"To use blastula with Gmail you will need to have an **app password created for your Gmail account**. An app password is a password generated by Google for the purpose of verifying an external app rather than using your standard password. Emails sent with only your standard password pair will be rejected by Google for security purposes. Note that to create an app password you will also need two factor authentication enabled for your account. To create an app password, follow the steps on the [Google Account Help page](https://support.google.com/accounts/answer/185833?hl=en).

Note: Previous versions of this document provided directions for using the Less Secure Apps setting in Gmail to allow sending blastula emails from Gmail accounts. **The Less Secure Apps setting has a sunset date of May 30, 2022** and the previous method will no longer work after that date. Any existing R code using blastula will need to be updated to use this new app password method."
