### ISSUE TITLE
non-UTF-8 subject in smtp_send() results in malformed email subject

### ISSUE THREAD

**Issue by shrektan** [rstudio/blastula#241]
**On Windows**, if the `subject` argument of `smtp_send()` is **not UTF-8** encoded, the received email's subject will become garbage letters.

However, after I add  `enc2utf8()` on the `subject` value, the received email becomes expected.

## Example

```r
smtp_send(subject = "中文")  # I have to provide `enc2utf8("中文")` as a workaround
```

### The malformed subject

![image](https://user-images.githubusercontent.com/8368933/100730050-82913500-3404-11eb-995c-a48966ee2663.png)

### Use enc2utf8()

![image](https://user-images.githubusercontent.com/8368933/100730015-773e0980-3404-11eb-9072-66ac3dc3fcaa.png)

**Comment by chuxinyuan** [comment]
我这边即使是用了`enc2utf8("中文")`依然会给出警告信息：

```
Warning message:
In sprintf("=?utf-8?B?%s?=", base64enc::base64encode(charToRaw(str)),  :
  one argument not used by format '=?utf-8?B?%s?='
```

**Comment by shrektan** [comment]
Your issue should have nothing to do with mine, as you are using Ubuntu where the native encoding is UTF-8, unlike Windows.

**Comment by chuxinyuan** [comment]
> Your issue should have nothing to do with mine, as you are using Ubuntu where the native encoding is UTF-8, unlike Windows.

因为我用的双系统，我要保证在Win和Ubuntu下都能运行，所以还是保留了`enc2utf8()`以防万一。我现在对mine.R里面的一行代码感到困惑：

```r
str <- sprintf("=?utf-8?B?%s?=", base64enc::base64encode(charToRaw(str)), 0)
```

每次都是这行代码报警示信息。

**Comment by chuxinyuan** [comment]
这个问题很久都没人解决了。

**Comment by chuxinyuan** [comment]
```
The email message was sent successfully.
Warning message:
In sprintf("=?utf-8?B?%s?=", base64enc::base64encode(charToRaw(str)),  :
  one argument not used by format '=?utf-8?B?%s?='
```
@rich-iannone @shrektan I don't know how to eliminate this prompt.
