### ISSUE TITLE
Prevent gmail clipped message?

### ISSUE THREAD

**Issue by j450h1** [rstudio/blastula#256]
Is there a way to format Rmarkdown documents or blastula settings to prevent this this type of clipping by gmail? 

![image](https://user-images.githubusercontent.com/7351530/113965072-8f25ff80-97e1-11eb-9275-319107d87a7c.png)

**Comment by j450h1** [comment]
Also when I click view entire message, I don't see the formatting expected but good enough. This same email appears completely fine in the iPhone mail client.

**Comment by fjbaron** [comment]
I have exactly the same issue happening in the last days. A few monts ago that didn't happen. Perhaps it is a change in gmail rendering?

**Comment by rich-iannone** [comment]
Could you provide the body of the message? Or the code used to generate the email?

**Comment by j450h1** [comment]
Unfortunately not - been too long

**Comment by rich-iannone** [comment]
Yeah! Two years... I'm finally catching up. I guess I'll close this but I'll be sure to test .Rmd rendered emails through Gmail during the next bit of work on this package.
