### ISSUE TITLE
Error 553

### ISSUE THREAD

**Issue by agronomofiorentini** [rstudio/blastula#275]
Hi and thanks to develop this R Package, is very useful and easy to use.

I am trying to send 1063 emails by using `smtp_send()` inside of a loop in order to send one email for each 1063 emails, so that each of them does not receive an email with the email contacts of all the emails.

After a series of emails, ranging between 20 - 60 emails I receive the following error.

> Error in curl_fetch_memory(smtp_server, handle = h) : RCPT failed: 553

I wanted to ask you if you can help me solve this problem, or find an alternative way to send all the emails.

Thanks,
Marco

**Comment by collinschwantes** [comment]
could you use bcc and chunk the emails into groups so that you are sending less than 20 emails?

**Comment by agronomofiorentini** [comment]
yes you were right, now it is working perfectly.

Thanks
