### ISSUE TITLE
[question] automated email send out

### ISSUE THREAD

**Issue by dominik-evert** [rstudio/blastula#278]
Hi there, 
i stumbled upon this package as an alternative to mailR. However, with mailR I was able to send mails by providing the password in the `send.mail()` function. 
If I send a mail with blastula's function `smtp_send()` , I am prompted to provide the password and have no option of passing it beforehand. This makes sending out automated email reports impossible. My question now: Is this really the case or am I just too blind to see the automation part. Any help or comment appreciated.

Best regards,
Dome

**Comment by javedmohib** [comment]
Hey @dominik-evert, you can use create_smtp_creds_key function to store SMTP credentials. Check this
https://cran.r-project.org/web/packages/blastula/vignettes/sending_using_smtp.html

The automation part becomes very useful if you use it with RStudio Connect. You can push the report there and schedule emails as per your need.
