### ISSUE TITLE
A file that email report read changes everyday

### ISSUE THREAD

**Issue by javedmohib** [rstudio/blastula#281]
Hey, thanks for developing this package. It is very useful. 

I am using this with RStudio connect to send reports to office colleagues every day. 

I was planning to use this for another project but the problem is that there is a file that changes every day so I will have to push the report to RStudio Connect every day. I was wondering if there is a way to read a file from my local server while the report is uploaded and scheduled on RStudio connect. 

If possible, this would extremely useful.

**Comment by rich-iannone** [comment]
This seems like a question outside the scope of the blastula package itself (obtaining data from another server). Could you ask the same question at https://community.rstudio.com ? Chances are, there are people there who have tried to solve the same problem.
