### ISSUE TITLE
Is there any way to configure a different "reply_to" email address?

### ISSUE THREAD

**Issue by klotzsche-useR** [rstudio/blastula#300]
smtp_send(
    from             = "jane@example.com",
    reply_to.      = "john@example.com",
    to                 = email_list,
    subject        = "Example Example",
    credentials = blastula_creds,
    verbose      = F
  )

**Comment by rich-iannone** [comment]
This is still a thing that needs to be done. There is a previous issue for that in https://github.com/rstudio/blastula/issues/113 so I will close this one. However, I am working on this package again so this issue will probably be worked on soon.
