### ISSUE TITLE
Attached files in email are all named "Filename" because of a mislabeled function parameter inside mime.R

### ISSUE THREAD

**Issue by jpd527** [rstudio/blastula#314]
https://github.com/rstudio/blastula/commit/0e1b1c705ea9a244105164aaae785d042c0a3ea7#r130328464

`str = "Filename",` needs to be changed to `fieldname = "Filename",` on line 104 of mime.R to fix the issue and properly label file attachments in the email.

**Comment by chuxinyuan** [comment]
same problem.

**Comment by mvellinger** [comment]
This is quite breaking, yes.

**Comment by tylerlittlefield** [comment]
For anyone that needs a quick fix, this is working for me on ubuntu:

```r
remotes::install_version("blastula", "0.3.3")
```

**Comment by b-rhodes** [comment]
Would this be worth releasing as 0.3.5? Seems like a pretty impactful issue
